# Generated by Django 4.2.4 on 2023-09-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typesofpuja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, null=True)),
                ('description', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=191, null=True)),
            ],
        ),
    ]
