# Generated by Django 4.2.4 on 2023-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_typesofpuja_name_typesofpuja_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesofpuja',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='typesofpuja',
            name='puja_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='typesofpuja',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
