# Generated by Django 4.2.4 on 2023-10-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_typesofpuja_category_typesofpuja_puja_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesofpuja',
            name='puja_img',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
