# Generated by Django 4.2.4 on 2024-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_typesofpuja_puja_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesofpuja',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
