# Generated by Django 4.2.4 on 2024-04-13 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingform',
            old_name='user_adress',
            new_name='user_address',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='puja_item',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='pujaname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
