# Generated by Django 4.2.4 on 2024-04-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_user_adress_bookingform_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='details',
        ),
    ]
